<a href="https://colab.research.google.com/github/iizmyy/blog/blob/master/algoritmaPemrograman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Input nilai tugas, nilai uts, dan nilai uas
n_tugas = input("Masukkan Nilai Tugas : ")
n_tugas = float(n_tugas)
n_uts = input("Masukkan Nilai UTS : ")
n_uts = float(n_uts)
n_uas = input("Masukkan Nilai UAS : ")
n_uas = float(n_uas)

# Hitung nilai akhir
n_akhir = (0.2*n_tugas) + (0.3 * n_uts) + (0.5 * n_uas)

# Cetak nilai akhir
print("Nilai akhir : ", n_akhir)

Masukkan Nilai Tugas : 80
Masukkan Nilai UTS : 80
Masukkan Nilai UAS : 90
Nilai akhir :  85.0


### Seleksi

In [ ]:
# Input total pembelian
total_bayar = input("Total Bayar : Rp.")
total_bayar = float(total_bayar)

# Hitung Diskon
if total_bayar >= 500000 :
  diskon = total_bayar * 0.1
elif total_bayar >= 200000 :
  diskon = total_bayar * 0.05
else :
  diskon = total_bayar * 0.02

# Hitung total bayar setelah diskon
total_bayar = total_bayar - diskon

# Cetak total bayar
print("Jumlah potongan : Rp.", diskon)
print("Total Pembayaran : Rp.", total_bayar)

Total Bayar : Rp.400000
Jumlah potongan : Rp. 20000.0
Total Pembayaran : Rp. 380000.0


In [ ]:
print("Toko Algoritma");
print("Jln. Kebenaran No. 10 Makassar")
print("\n")
print("Daftar Pembelian")

tambah = 'y'
i = 1
total = 0
while(tambah=='y' or tambah=='Y'):
  print("No.", i)
  nama = input("Nama Barang : ")
  jumlah = input("Jumlah : ")
  harga_satu = input("Harga Satuan : ")
  jumlah = int(jumlah)
  harga_satu = int(harga_satu)
  jum_harga = jumlah * harga_satu
  print("Jumlah Harga : ", jum_harga)
  tambah = input("\nTambah Barang ? : ")
  total += jum_harga
  i+=1
print("Total Bayar : Rp. ", total)
bayar = input("Bayar : Rp. ")
bayar = int(bayar)
kembali = bayar-total
print("Kembali : Rp. ", kembali)


Toko Algoritma
Jln. Kebenaran No. 10 Makassar


Daftar Pembelian
No. 1
Nama Barang : Sabun
Jumlah : 3
Harga Satuan : 3500
Jumlah Harga :  10500

Tambah Barang ? : y
No. 2
Nama Barang : Roti
Jumlah : 1
Harga Satuan : 10000
Jumlah Harga :  10000

Tambah Barang ? : t
Total Bayar : Rp.  20500
Bayar : Rp. 50000
Kembali : Rp.  29500


### Prosedur dan Fungsi

In [ ]:
def inputData():
  nama = input("Nama Karyawan : ")
  id_jab = input("ID Jabatan [SE/PM/DA] : ")
  jam_lembur = input("Jumlah Lembur (jam) : ")
  jam_lembur = int(jam_lembur)
  
  return nama, id_jab, jam_lembur

def hitungGaji():
  if id_jab == 'SE':
    jabatan = 'Software Engineering'
    gapok = 20000000
    lembur_per_jam = 500000
  elif id_jab == 'PM':
    jabatan = 'Programmer'
    gapok = 10000000
    lembur_per_jam = 200000
  else :
    jabatan = 'Database Designer'
    gapok = 10000000
    lembur_per_jam = 250000

  gaji = gapok + (jam_lembur * lembur_per_jam)

  return jabatan, gaji
  
def cetakDataGaji():
  print("Nama Karyawan :", nama)
  print("Jabatan :", jabatan)
  print("Total Gaji: Rp. ", gaji)

nama, id_jab, jam_lembur = inputData()
jabatan, gaji = hitungGaji()
print("----------------------\n")
cetakDataGaji()


Nama Karyawan : Andika
ID Jabatan [SE/PM/DA] : SE
Jumlah Lembur (jam) : 4
----------------------

Nama Karyawan : Andika
Jabatan : Software Engineering
Total Gaji: Rp.  22000000


### Array

In [ ]:
import numpy as np

def isiArray(n):
    arr = np.array([])
    for i in range(n) :
        elemen = input("Masukkan elemen ke-" + str(i+1)+" ")
        elemen = int(elemen)
        arr = np.append(arr, elemen)
    return arr

def cetakArray(arr) :
    for a in arr:
        print(a)
        
def gabungArray(arr1, arr2) :
    n = arr1.size
    m = arr2.size
    arr = np.array([])
    # Salin isi arr1 ke array gabungan
    for i in range(n):
        arr = np.append(arr, arr1[i])
    # Salin isi arr2 ke array gabungan
    for i in range(m):
        arr = np.append(arr, arr2[i])
    return arr

def sortArray(arr):
    n = arr.size
    for i in range (n-1):
        for j in range (i+1,n):
            if (arr[i]>arr[j]) :
                temp = arr[i]
                arr[i] = arr[j]
                arr[j] = temp
    return arr

def cariElemen(arr, elemen):
    indikator = 'N'
    indeks = 0;
    n = arr.size
    while(indikator=='N' and indeks < n ):
        if(arr[indeks] == elemen):
            posisi = indeks+1
            indikator = 'Y'
        indeks += 1kharisma.ac.id/
    if indikator == 'N':
        posisi = "Elemen tidak ditemukan"
    return posisi

# Input Elemen Array
print("Input Elemen Array")
nilai = np.array([])
nilai = isiArray(10)

# Mencetak Isi Array
print("Isi Array :")
cetakArray(nilai)

# Mengurutkan isi Array
print("Array setelah diurutkan :")
sortedArray = sortArray(nilai)
print(sortedArray)

# Mencari isi Array
angka = 9
posisi = cariElemen(nilai, angka)
print("Elemen {} berada pada indeks ke- : {}".format(angka, posisi))

#Gabung Array
print("Array setelah digabung")
nilai1 = np.array([3,4])
gabungArr = gabungArray(nilai, nilai1)
print(gabungArr)

Input Elemen Array
Masukkan elemen ke-1 7
Masukkan elemen ke-2 12
Masukkan elemen ke-3 15
Masukkan elemen ke-4 7
Masukkan elemen ke-5 1
Masukkan elemen ke-6 2
Masukkan elemen ke-7 5
Masukkan elemen ke-8 4
Masukkan elemen ke-9 8
Masukkan elemen ke-10 6
Isi Array :
7.0
12.0
15.0
7.0
1.0
2.0
5.0
4.0
8.0
6.0
Array setelah diurutkan :
[ 1.  2.  4.  5.  6.  7.  7.  8. 12. 15.]
Elemen 9 berada pada indeks ke- : Elemen tidak ditemukan
Array setelah digabung
[ 1.  2.  4.  5.  6.  7.  7.  8. 12. 15.  3.  4.]


### Array 2D

In [ ]:
import numpy as np

def isiArrayDD(n, m):
  arr = np.array([[]])
  for baris in range(n):
    arr1D = np.array([])
    for kolom in range(m):
      elemen = input("Masukkan elemen baris ke-{} kolom ke-{} : ".format(baris+1, kolom+1))
      elemen = int(elemen)
      arr = np.append(arr, elemen)
  arr = np.reshape(arr, (n,m))
  return arr

def cetakArrayDD(n, m, arr):
  for baris in range(n):
    for kolom in range(m):
      print(arr[baris,kolom], end='  ')
    print()

#Mengisi Data Suhu
print("Input Data Suhu")
array2D = isiArrayDD(3,4)

#Mencetak Data Suhu
print("Data Suhu Udara Selama 3 Hari")
cetakArrayDD(3,4, array2D)

Input Data Suhu
Masukkan elemen baris ke-1 kolom ke-1 : 25
Masukkan elemen baris ke-1 kolom ke-2 : 31
Masukkan elemen baris ke-1 kolom ke-3 : 30
Masukkan elemen baris ke-1 kolom ke-4 : 26
Masukkan elemen baris ke-2 kolom ke-1 : 24
Masukkan elemen baris ke-2 kolom ke-2 : 28
Masukkan elemen baris ke-2 kolom ke-3 : 27
Masukkan elemen baris ke-2 kolom ke-4 : 23
Masukkan elemen baris ke-3 kolom ke-1 : 23
Masukkan elemen baris ke-3 kolom ke-2 : 26
Masukkan elemen baris ke-3 kolom ke-3 : 25
Masukkan elemen baris ke-3 kolom ke-4 : 24
Data Suhu Udara Selama 3 Hari
25.0  31.0  30.0  26.0  
24.0  28.0  27.0  23.0  
23.0  26.0  25.0  24.0  


### Linear Search


In [ ]:
import numpy as np

#Input Elemen Data ke Array arr
n = 12
arr = np.array([])
for i in range(n) :
  elemen = input("Masukkan elemen ke-" + str(i+1)+" : ")
  elemen = int(elemen)
  arr = np.append(arr, elemen)

# Input data yang dicari
x = input("Masukkan data yang dicari :")
x = int(x)

# Mencari data x dalam array arr
indeks=0;
ditemukan = False
while(indeks < n-1 and arr[indeks] != x ):
  indeks+=1

if(arr[indeks] == x):
  ditemukan = True

if(ditemukan == True):
  print("Data ditemukan pada elemen ke-", indeks+1)
else:
    print("Data tidak ditemukan")


Masukkan elemen ke-1 : 5
Masukkan elemen ke-2 : 10
Masukkan elemen ke-3 : 1
Masukkan elemen ke-4 : 10
Masukkan elemen ke-5 : 15
Masukkan elemen ke-6 : 2
Masukkan elemen ke-7 : 15
Masukkan elemen ke-8 : 20
Masukkan elemen ke-9 : 3
Masukkan elemen ke-10 : 20
Masukkan elemen ke-11 : 25
Masukkan elemen ke-12 : 4
Masukkan data yang dicari :3
Data ditemukan pada elemen ke- 9


###Binary Search

In [ ]:
import numpy as np
import math

arr = np.array([32,2,10,5,3,12,30,14,1,33])
sorted_arr = np.sort(arr) # mengurutkan isi array
idx1 = 0
idx2 = arr.size-1
index = math.ceil(idx2/2)
ditemukan = False

# Input data yang dicari
x = input("Masukkan data yang dicari :")
x = int(x)

# Baca Data
print("Data Terurut : ")
for i in range(arr.size):
  print(sorted_arr[i], end=" ")
print()

while(ditemukan==False and (idx1 <= idx2)) :
  indeks = math.ceil((idx1 + idx2)/2)
  if(x==sorted_arr[indeks]):
    ditemukan = True
  elif (x > sorted_arr[indeks]):
    idx1 = indeks+1
  else :
    idx2 = indeks-1
if(ditemukan == True):
  print("Data ditemukan di posisi :", indeks+1)
else :
  print("Data tidak ditemukan")


Masukkan data yang dicari :75
Data Terurut : 
1 2 3 5 10 12 14 30 32 33 
Data tidak ditemukan


### Bubble Sort

In [ ]:
import numpy as np

arr = np.array([10,25,9,17,11,3])

def bubbleSort(vArray):
    maks = vArray.size
    for i in range(maks-1):
        print("Loop ", i+1)
        for indeks in range(maks-1):
            if(vArray[indeks]>vArray[indeks+1]):
                temp = vArray[indeks]
                vArray[indeks] = vArray[indeks+1]
                vArray[indeks+1] = temp
                #vArray[[indeks, indeks+1]] = vArray[[indeks+1, indeks]] 
            print(vArray)
        maks-=1
    return vArray

print("Array Sebelum diurutkan : ", arr)
print("Array setelah diurutkan : ", bubbleSort(arr))

Array Sebelum diurutkan :  [10 25  9 17 11  3]
Loop  1
[10 25  9 17 11  3]
[10  9 25 17 11  3]
[10  9 17 25 11  3]
[10  9 17 11 25  3]
[10  9 17 11  3 25]
Loop  2
[ 9 10 17 11  3 25]
[ 9 10 17 11  3 25]
[ 9 10 11 17  3 25]
[ 9 10 11  3 17 25]
Loop  3
[ 9 10 11  3 17 25]
[ 9 10 11  3 17 25]
[ 9 10  3 11 17 25]
Loop  4
[ 9 10  3 11 17 25]
[ 9  3 10 11 17 25]
Loop  5
[ 3  9 10 11 17 25]
Array setelah diurutkan :  [ 3  9 10 11 17 25]


### Selection Sort

In [ ]:
import numpy as np

arr = np.array([10,25,9,17,11,3])

def selectionSort(vArray):
  maks = vArray.size
  for i in range(maks-1):
    iMin = i;
    print("Loop ", i+1)
    for indeks in range(i+1, maks):
      if(vArray[indeks] < vArray[iMin]):
        iMin = indeks
    if(i != iMin ) :
      vArray[[i, iMin]] = vArray[[iMin, i]] 
    print(vArray)
  return vArray

print("Array Sebelum diurutkan : ", arr)
print("Array setelah diurutkan : ", selectionSort(arr))

Array Sebelum diurutkan :  [10 25  9 17 11  3]
Loop  1
[ 3 25  9 17 11 10]
Loop  2
[ 3  9 25 17 11 10]
Loop  3
[ 3  9 10 17 11 25]
Loop  4
[ 3  9 10 11 17 25]
Loop  5
[ 3  9 10 11 17 25]
Array setelah diurutkan :  [ 3  9 10 11 17 25]


### Insertion Sort

In [ ]:
import numpy as np

arr = np.array([10,25,9,17,11,3])

def insertionSort(vArray):
  for posisi in range(1,vArray.size):
    print("Loop ", posisi)
    x = vArray[posisi];
    idx = 0;
    # Cari posisi penyisipan elemen x
    while(x > vArray[idx] and idx < posisi):
      idx+=1
    # Geser dan sisipkan elemen-elemen data
    if(x <= arr[idx]):
      for k in range(posisi,idx,-1):
        vArray[k] = vArray[k-1]
      vArray[idx] = x
      #print("Ambil elemen ke-{} : {}".format(posisi+1,x))
      print(vArray)
  return vArray

print("Array Sebelum diurutkan : ", arr)
print("Array setelah diurutkan : ", insertionSort(arr))

Array Sebelum diurutkan :  [10 25  9 17 11  3]
Loop  1
[10 25  9 17 11  3]
Loop  2
[ 9 10 25 17 11  3]
Loop  3
[ 9 10 17 25 11  3]
Loop  4
[ 9 10 11 17 25  3]
Loop  5
[ 3  9 10 11 17 25]
Array setelah diurutkan :  [ 3  9 10 11 17 25]


#### Merge Sort

In [ ]:
import numpy as np
import math

def mergeSort(vArray, awal, akhir):
  if(awal < akhir):
    mid = math.floor((awal+akhir)/2)
    #print(vArray[awal:akhir+1])
    mergeSort(vArray, awal, mid)
    mergeSort(vArray, mid+1, akhir)
    vArray = merge(vArray, awal, mid, akhir)
    return vArray


def merge(vArray, awal, mid, akhir):
  lArray = np.array([])
  rArray = np.array([])

  n1 = mid-awal+1
  n2 = akhir-mid
  for i in range(n1):
    lArray = np.append(lArray, vArray[awal+i])
  for j in range(n2):
    rArray = np.append(rArray, vArray[mid+1+j])
  i = j =  0
  k = awal
  print(lArray, rArray)
  while(i < n1 and j < n2):
    if(lArray[i] <= rArray[j]):
      vArray[k] = lArray[i]
      i+=1
    else:
      vArray[k] = rArray[j]
      j+=1
    k+=1

  while(i < n1):
    vArray[k] = lArray[i]
    i+=1
    k+=1
  
  while(j < n2):
    vArray[k] = rArray[j]
    j+=1
    k+=1
  return vArray

if __name__ == "__main__":
  #arr = np.array([10,25,9,17,11,3])
  #arr = np.array([33,14,27,10,35,19,44,42])
  arr = np.array([15,40,21,3,42,18,45,50])
  awal=0
  akhir=arr.size-1
  print("Array belum terurut : ", arr)
  sortedArray = mergeSort(arr,awal,akhir)
  #print(sortedArray)
  print("Array setelah diurutkan : ", sortedArray)

Array belum terurut :  [15 40 21  3 42 18 45 50]
[15.] [40.]
[21.] [3.]
[15. 40.] [ 3. 21.]
[42.] [18.]
[45.] [50.]
[18. 42.] [45. 50.]
[ 3. 15. 21. 40.] [18. 42. 45. 50.]
Array setelah diurutkan :  [ 3 15 18 21 40 42 45 50]


### Quick Sort

In [16]:
import numpy as np
import math

def quickSort(vArray, indeksKiri, indeksKanan):
  if(indeksKiri < indeksKanan):
    indeksPivot = partisi(vArray, indeksKiri, indeksKanan)
    quickSort(vArray, indeksKiri, indeksPivot-1)
    quickSort(vArray, indeksPivot, indeksKanan)

def partisi(vArray, indeksKiri, indeksKanan):
  indeksPivot = indeksKanan
  indeks = indeksKiri
  print("Pivot : ", vArray[indeksPivot]) # Mencetak Pivot
  print(vArray[indeksKiri:indeksKanan+1]) # Mencetak Partisi
  for i in range (indeksKiri, indeksKanan+1):
    if(vArray[i] < vArray[indeksPivot]):
      vArray[[i, indeks]] = vArray[[indeks, i]]
      indeks+=1
  vArray[[indeksPivot, indeks]] = vArray[[indeks, indeksPivot]]
  return indeks

if __name__ == "__main__":
  arr = np.array([15,70,35,80,42,38,45,58])
  awal=0
  akhir=arr.size-1
  print("Array belum terurut : ", arr)
  quickSort(arr,awal,akhir)
  print("Array setelah diurutkan : ", arr)

Array belum terurut :  [15 70 35 80 42 38 45 58]
Pivot :  58
[15 70 35 80 42 38 45 58]
Pivot :  45
[15 35 42 38 45]
Pivot :  38
[15 35 42 38]
Pivot :  35
[15 35]
Pivot :  42
[38 42]
Pivot :  80
[58 70 80]
Pivot :  70
[58 70]
Array setelah diurutkan :  [15 35 38 42 45 58 70 80]
